-- Seed EgyTex products
insert into public.products (id, name, description, full_description, price, image, category, stock, is_new, is_featured, created_at) values

('kunafa-bil-qeshta', 'Kunafa bil Qeshta', 'Classic shredded-pastry kunafa filled with rich cream and soaked in rose-water syrup.', 'Our signature Kunafa bil Qeshta is a beloved Egyptian dessert crafted from golden shredded kataifi pastry layered over a silky qeshta (clotted cream) filling. Each tray is baked to a perfect crisp and drenched in fragrant rose-water and orange-blossom syrup. Topped with crushed pistachios for added crunch. Made fresh every morning and best enjoyed warm. Serves 2–3 people.', 85.00, 'https://placehold.co/600x450/C8960C/FFFFFF/png?text=Kunafa%20bil%20Qeshta', 'sweet-food', 30, true, true, '2026-01-15T00:00:00Z'),

('chocolate-fudge-cake', 'Chocolate Fudge Cake', 'Rich triple-layer chocolate cake with velvety ganache frosting.', 'A dream for chocolate lovers — our Chocolate Fudge Cake is built from three moist layers of dark cocoa sponge, each sandwiched with a luscious Belgian chocolate ganache. The outside is coated in a glossy fudge frosting and decorated with chocolate shavings. Baked fresh to order using premium cocoa and real butter. Serves 8–10 people. Available with a personalized message.', 150.00, 'https://placehold.co/600x450/1C1400/F0C040/png?text=Chocolate%20Fudge%20Cake', 'sweet-food', 15, false, true, '2026-01-14T00:00:00Z'),

('baklava-box-12', 'Baklava Box (12 pcs)', 'Assorted baklava with walnuts, pistachios, and cashews in a gift-ready box.', 'Our Baklava Box contains 12 hand-crafted pieces featuring three classic varieties: walnut, pistachio, and cashew, all layered in golden phyllo pastry and drenched in honey-orange syrup. Each piece is individually cut and arranged in an elegant box — perfect as a gift or a personal treat. Made daily using traditional Egyptian family recipes. Stays fresh for up to 5 days.', 120.00, 'https://placehold.co/600x450/C8960C/FFFFFF/png?text=Baklava%20Box', 'sweet-food', 25, true, true, '2026-01-13T00:00:00Z'),

('om-ali', 'Om Ali', 'Traditional Egyptian bread pudding with nuts, coconut, and cream, baked until golden.', 'Om Ali is Egypt''s most cherished dessert — a warm, comforting bake of torn puff pastry soaked in sweetened milk and cream, layered with a generous mix of toasted almonds, hazelnuts, raisins, and shredded coconut. Our version is baked in individual portions until the top is beautifully golden. Served hot for the best experience. A true taste of Egyptian home cooking.', 70.00, 'https://placehold.co/600x450/C8960C/FFFFFF/png?text=Om%20Ali', 'sweet-food', 20, true, false, '2026-01-12T00:00:00Z'),

('birthday-layer-cake', 'Birthday Layer Cake', 'Custom celebration cake with vanilla sponge, fresh cream, and fruit decoration.', 'Make every celebration unforgettable with our Birthday Layer Cake. Three tall layers of fluffy vanilla sponge are filled with light diplomat cream and fresh seasonal fruit, then dressed in smooth whipped cream frosting. Decorated with edible gold accents and your choice of message. Available in sizes for 10–20 people. Order at least 24 hours in advance for personalization.', 280.00, 'https://placehold.co/600x450/1C1400/F0C040/png?text=Birthday%20Cake', 'sweet-food', 8, false, true, '2026-01-11T00:00:00Z'),

('cheese-kunafa', 'Cheese Kunafa', 'Golden kunafa stuffed with stretchy akkawi cheese and sweet syrup.', 'A bolder take on the classic, our Cheese Kunafa is packed with fresh akkawi cheese that melts and stretches with every bite. The kataifi crust is pressed thin and fried to a perfect golden crisp before being generously doused in sugar syrup. Finished with a sprinkle of crushed pistachios. Popular at weddings, gatherings, and as an indulgent everyday treat. Serves 2–4.', 95.00, 'https://placehold.co/600x450/C8960C/FFFFFF/png?text=Cheese%20Kunafa', 'sweet-food', 22, true, false, '2026-01-10T00:00:00Z'),

('chicken-shawarma-sandwich', 'Chicken Shawarma Sandwich', 'Marinated grilled chicken wrapped in soft bread with garlic sauce and pickles.', 'Our Chicken Shawarma Sandwich features tender strips of chicken marinated overnight in a blend of Egyptian spices — cumin, turmeric, garlic, and coriander — then slow-roasted on a vertical spit. Served in freshly baked soft bread with creamy garlic sauce, crunchy pickles, and a house tomato salsa. A Cairo street-food staple, elevated. Made to order for maximum freshness.', 65.00, 'https://placehold.co/600x450/1C1400/F0C040/png?text=Chicken%20Shawarma', 'savory-food', 40, true, false, '2026-01-09T00:00:00Z'),

('grilled-kofta-meal', 'Grilled Kofta Meal', 'Juicy beef and lamb kofta skewers served with rice, salad, and tahini.', 'A hearty Egyptian classic — seasoned ground beef and lamb kofta skewers, grilled over charcoal for a rich smoky flavor. Served with steamed white rice, a fresh tomato and cucumber salad, warm flatbread, and a generous drizzle of tahini sauce. Each portion includes four kofta skewers. Our kitchen uses local, freshly ground meat prepared each morning.', 110.00, 'https://placehold.co/600x450/1C1400/F0C040/png?text=Grilled%20Kofta', 'savory-food', 18, false, false, '2026-01-08T00:00:00Z'),

('cheese-feteer', 'Cheese Feteer', 'Flaky layered Egyptian feteer pastry stuffed with a blend of creamy cheeses.', 'Feteer Meshaltet is Egypt''s iconic flaky pastry, and our Cheese Feteer is one of its finest savory forms. Dozens of paper-thin layers of hand-pulled dough are filled with a rich mixture of akkawi and rumi cheeses, then baked in a stone oven until puffed and golden. Best served hot, torn apart by hand. Pairs perfectly with a cup of tea. Made fresh throughout the day.', 75.00, 'https://placehold.co/600x450/C8960C/FFFFFF/png?text=Cheese%20Feteer', 'savory-food', 30, true, false, '2026-01-07T00:00:00Z'),

('mixed-grill-platter', 'Mixed Grill Platter', 'A generous platter of kofta, chicken, and lamb chops fresh off the charcoal grill.', 'Our Mixed Grill Platter is the ultimate sharing meal — a large platter loaded with charcoal-grilled kofta skewers, marinated chicken thighs, and tender lamb chops. Accompanied by Egyptian rice, roasted vegetables, fresh salad, warm bread, and dipping sauces. Perfect for two hungry diners or a light meal for three. Every item is seasoned with our signature spice blend and grilled to order.', 195.00, 'https://placehold.co/600x450/1C1400/F0C040/png?text=Mixed%20Grill', 'savory-food', 12, true, false, '2026-01-06T00:00:00Z'),

('falafel-sandwich', 'Falafel Sandwich', 'Crispy falafel in warm bread with tahini, tomatoes, and fresh herbs.', 'Our falafel is made from scratch using soaked fava beans and chickpeas blended with fresh parsley, coriander, and a secret spice mix — then deep-fried to a crisp golden exterior with a soft, fluffy interior. Served in warm flatbread with drizzled tahini, sliced tomatoes, crunchy pickled cucumber, and a handful of fresh herbs. A classic Egyptian breakfast and all-day snack.', 30.00, 'https://placehold.co/600x450/C8960C/FFFFFF/png?text=Falafel%20Sandwich', 'savory-food', 50, false, false, '2026-01-05T00:00:00Z'),

('rice-grilled-chicken', 'Rice with Grilled Chicken', 'Herb-marinated half chicken served with fragrant Egyptian rice and grilled vegetables.', 'A satisfying, wholesome meal — half a free-range chicken marinated in a blend of garlic, lemon, and Egyptian seven-spice, then grilled until the skin is charred and the meat is juicy throughout. Served on a bed of fragrant Egyptian rice cooked with vermicelli and topped with caramelized onions. Comes with grilled tomato, green peppers, and a fresh salad. Comfort food at its best.', 95.00, 'https://placehold.co/600x450/1C1400/F0C040/png?text=Rice%20%26%20Chicken', 'savory-food', 20, true, false, '2026-01-03T00:00:00Z')

on conflict (id) do nothing;
